<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_SECRET' => 'thiscanbewhatyouwant',
  'DATABASE_URL' => (getenv('DATABASE_URL')),
);